name: Build

# When to run this Workflow...
on:

  # Run this Workflow when files are updated (Pushed) in this Branch
  push:
    branches: [ master ]
    
  # Also run this Workflow when a Pull Request is created or updated in this Branch
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #  TODO: Fix build error for pycryptodomex in macos-latest
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
      with:
        #  Recursive checkout needed for LVGL in sdk_app_st7789
        submodules: 'recursive'

    - run: make
      working-directory: customer_app
      env:
        BL60X_SDK_PATH: ${{ github.workspace }}
        
    - name: Upload Built Firmware
      uses: actions/upload-artifact@v2
      with:
        name: customer_app.zip
        path: |
          customer_app/**/*.bin
          customer_app/**/*.elf
      
  build-msys:
    runs-on: windows-latest
    steps:
    - name: setup msys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: make
        msystem: MSYS

    - uses: actions/checkout@v2
      with:
        #  Recursive checkout needed for LVGL in sdk_app_st7789
        submodules: 'recursive'

    - run: make
      shell: msys2 {0}
      working-directory: customer_app
      env:
        BL60X_SDK_PATH: ${{ github.workspace }}
        MAX_MAKE_JOBS: 2
